# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-30 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='org',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
