# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-29 22:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='课程类别')),
                ('nick', models.CharField(max_length=30, verbose_name='id')),
                ('desc', models.CharField(max_length=50, verbose_name='描述')),
                ('image', models.ImageField(max_length=200, upload_to='fengmian/', verbose_name='分类')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '课程分类',
                'verbose_name_plural': '课程分类',
            },
        ),
    ]
