# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-09 13:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('author', models.CharField(max_length=10, verbose_name='作者')),
                ('readNum', models.ImageField(max_length=5, upload_to='', verbose_name='阅读人数')),
                ('pinglunNum', models.ImageField(max_length=5, upload_to='', verbose_name='评论人数')),
                ('shareNum', models.ImageField(max_length=5, upload_to='', verbose_name='分享人数')),
                ('content', models.TextField(max_length=100, verbose_name='内容')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '文章手记',
                'verbose_name_plural': '文章手记',
            },
        ),
    ]
