# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-09 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='content',
            field=models.TextField(max_length=500, verbose_name='课程详情'),
        ),
    ]
