# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-06 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_usernotecomment_wxopenid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotecomment',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.StudentProfile', verbose_name='用户'),
        ),
    ]
