# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-30 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='user_list',
            field=models.TextField(blank=True, default='', null=True, verbose_name='学生学习自动加入该列表'),
        ),
    ]
