# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-30 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180430_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='章节描述'),
        ),
        migrations.AlterField(
            model_name='lessonrecord',
            name='video_url',
            field=models.FileField(upload_to='video/course/%Y/%m', verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.FileField(upload_to='video/course/%Y/%m', verbose_name='视频'),
        ),
    ]
