# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-08 21:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_auto_20180430_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='examUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.CharField(blank=True, max_length=40, null=True, verbose_name='学员姓名')),
                ('choise_type', models.CharField(default='单选', max_length=20, verbose_name='选择题类型')),
                ('choise_name', models.TextField(max_length=30, verbose_name='选择题题目')),
                ('answer_a', models.CharField(default='A', max_length=2, verbose_name='A')),
                ('answer_b', models.CharField(default='B', max_length=2, verbose_name='B')),
                ('answer', models.CharField(choices=[('yes', '正确'), ('no', '错误')], max_length=6, verbose_name='答案是:')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('courseName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程名称')),
            ],
            options={
                'verbose_name': '单选题',
                'verbose_name_plural': '单选题',
            },
        ),
    ]
