# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-08 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examunit',
            name='answer',
            field=models.CharField(choices=[('A', '正确'), ('B', '错误')], max_length=6, verbose_name='答案是:'),
        ),
    ]
