# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-17 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='study_course',
            field=models.CharField(default='', max_length=10, verbose_name='学习课程编号'),
        ),
    ]
