# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-18 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_studentprofile_study_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='study_course',
            field=models.CharField(default='', max_length=150, verbose_name='学习课程编号'),
        ),
    ]
